#############################################################################
# Makefile for building: qt
# Generated by qmake (2.01a) (Qt 4.8.5) on: Thu Dec 14 22:47:02 2017
# Project:  qt.pro
# Template: app
# Command: /depot/qt-everywhere-opensource-4.8.5/amd64/bin/qmake -o Makefile qt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/linux-g++ -I. -I/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/include/QtCore -I/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/include/QtGui -I/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/depot/qt-everywhere-opensource-4.8.5/amd64/lib
LIBS          = $(SUBLIBS)  -L/depot/qt-everywhere-opensource-4.8.5/amd64/lib -lQtGui -L/depot/qt-everywhere-opensource-4.8.5/amd64/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /depot/qt-everywhere-opensource-4.8.5/amd64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = board.cpp \
		cell.cpp \
		game.cpp \
		level.cpp \
		main.cpp \
		maze.cpp \
		menu.cpp \
		player.cpp \
		players.cpp \
		score.cpp \
		win.cpp \
		window.cpp moc_board.cpp \
		moc_game.cpp \
		moc_menu.cpp \
		moc_players.cpp \
		moc_score.cpp \
		moc_win.cpp \
		moc_window.cpp
OBJECTS       = board.o \
		cell.o \
		game.o \
		level.o \
		main.o \
		maze.o \
		menu.o \
		player.o \
		players.o \
		score.o \
		win.o \
		window.o \
		moc_board.o \
		moc_game.o \
		moc_menu.o \
		moc_players.o \
		moc_score.o \
		moc_win.o \
		moc_window.o
DIST          = /depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/linux.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base-unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-base.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/qconfig.pri \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/modules/qt_webkit_version.pri \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_functions.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_config.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/exclusive_builds.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_pre.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/release.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_post.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/shared.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/warn_on.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/thread.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/moc.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/resources.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/uic.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/yacc.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/lex.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/include_source_dir.prf \
		qt.pro
QMAKE_TARGET  = qt
DESTDIR       = 
TARGET        = qt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt.pro  /depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/linux-g++/qmake.conf /depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/linux.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base-unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-base.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-unix.conf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/qconfig.pri \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/modules/qt_webkit_version.pri \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_functions.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_config.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/exclusive_builds.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_pre.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/release.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_post.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/shared.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/warn_on.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/thread.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/moc.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/resources.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/uic.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/yacc.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/lex.prf \
		/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/include_source_dir.prf \
		/depot/qt-everywhere-opensource-4.8.5/amd64/lib/libQtGui.prl \
		/depot/qt-everywhere-opensource-4.8.5/amd64/lib/libQtCore.prl
	$(QMAKE) -o Makefile qt.pro
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/unix.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/linux.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/gcc-base-unix.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-base.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/common/g++-unix.conf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/qconfig.pri:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/modules/qt_webkit_version.pri:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_functions.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt_config.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/exclusive_builds.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_pre.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/release.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/default_post.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/shared.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/gdb_dwarf_index.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/warn_on.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/qt.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/unix/thread.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/moc.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/resources.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/uic.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/yacc.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/lex.prf:
/depotbld/RHEL5.5/qt-everywhere-opensource-4.8.5/amd64/mkspecs/features/include_source_dir.prf:
/depot/qt-everywhere-opensource-4.8.5/amd64/lib/libQtGui.prl:
/depot/qt-everywhere-opensource-4.8.5/amd64/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt1.0.0 || $(MKDIR) .tmp/qt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt1.0.0/ && $(COPY_FILE) --parents board.hpp cell.hpp game.hpp level.hpp maze.hpp menu.hpp player.hpp players.hpp score.hpp win.hpp window.hpp .tmp/qt1.0.0/ && $(COPY_FILE) --parents board.cpp cell.cpp game.cpp level.cpp main.cpp maze.cpp menu.cpp player.cpp players.cpp score.cpp win.cpp window.cpp .tmp/qt1.0.0/ && (cd `dirname .tmp/qt1.0.0` && $(TAR) qt1.0.0.tar qt1.0.0 && $(COMPRESS) qt1.0.0.tar) && $(MOVE) `dirname .tmp/qt1.0.0`/qt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_board.cpp moc_game.cpp moc_menu.cpp moc_players.cpp moc_score.cpp moc_win.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_board.cpp moc_game.cpp moc_menu.cpp moc_players.cpp moc_score.cpp moc_win.cpp moc_window.cpp
moc_board.cpp: board.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) board.hpp -o moc_board.cpp

moc_game.cpp: board.hpp \
		menu.hpp \
		win.hpp \
		score.hpp \
		players.hpp \
		game.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) game.hpp -o moc_game.cpp

moc_menu.cpp: menu.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) menu.hpp -o moc_menu.cpp

moc_players.cpp: players.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) players.hpp -o moc_players.cpp

moc_score.cpp: score.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) score.hpp -o moc_score.cpp

moc_win.cpp: win.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) win.hpp -o moc_win.cpp

moc_window.cpp: window.hpp
	/depot/qt-everywhere-opensource-4.8.5/amd64/bin/moc $(DEFINES) $(INCPATH) window.hpp -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

board.o: board.cpp board.hpp \
		maze.hpp \
		cell.hpp \
		player.hpp \
		level.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

cell.o: cell.cpp cell.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o cell.cpp

game.o: game.cpp game.hpp \
		board.hpp \
		menu.hpp \
		win.hpp \
		score.hpp \
		players.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

level.o: level.cpp level.hpp \
		board.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level.o level.cpp

main.o: main.cpp window.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

maze.o: maze.cpp maze.hpp \
		cell.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maze.o maze.cpp

menu.o: menu.cpp menu.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o menu.cpp

player.o: player.cpp player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

players.o: players.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o players.o players.cpp

score.o: score.cpp score.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o score.o score.cpp

win.o: win.cpp win.hpp \
		game.hpp \
		board.hpp \
		menu.hpp \
		score.hpp \
		players.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win.o win.cpp

window.o: window.cpp window.hpp \
		game.hpp \
		board.hpp \
		menu.hpp \
		win.hpp \
		score.hpp \
		players.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_board.o: moc_board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_board.o moc_board.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_menu.o: moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o moc_menu.cpp

moc_players.o: moc_players.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_players.o moc_players.cpp

moc_score.o: moc_score.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_score.o moc_score.cpp

moc_win.o: moc_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win.o moc_win.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

